baseURL = "https://analytics-abc.xyz"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Georgy Toporkov"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = ["anatole", "matomo"]

[params.matomo]
url = "https://matomo.analytics-abc.xyz"
id = 1

[params.matomo.track]
button = "Allow ethical data collection"
message = "Don't worry, it's opensource analytics, it's not collecting *any* personal data at all, and not giving it to any 3d party."
[params.matomo.block]
button = "Disallow data collection"
message = "You're *not* tracked."

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
