  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/ru/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/ru/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/ru/about/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/ru/imprint/"
